### ISSUE TITLE
Build for production failed

### ISSUE THREAD

**Issue by tomysmile** [geeklearningio/gl-ionic2-env-configuration#2]
Hi, i am currently using ionic 2 RC 4. I have followed the instruction and it runs well on development mode, but when I tried to build in production ```e.g ionic run android --prod``` it failed.

```
[17:41:38]  build prod failed: Error encountered resolving symbol values statically. Reference to a local (non-exported)
            symbol 'GLIonic2EnvConfigurationModule'. Consider exporting the symbol (position 30:14 in the original .ts file), resolving symbol GLIonic2EnvConfigurationModule in
            /Users/tomyismail/my-app/node_modules/gl-ionic2-env-configuration/dist/gl-ionic2-env-configuration.module.d.ts,
...
...
```

below is my ionic information:

```
$ ionic info

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

Thanks.

**Comment by mosinski** [comment]
Hi same here,
command `node copy-env-config.js --env test` works fine and server runs correctly
but when I try to build project I got error:
```
[11:46:48]  Error: Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 
            'GLIonic2EnvConfigurationModule'. Consider exporting the symbol (position 30:14 in the original .ts file), 
            resolving symbol GLIonic2EnvConfigurationModule in 
            /home/osboxes/Desktop/my_app/node_modules/gl-ionic2-env-configuration/dist/gl-ionic2-env-configuration.module.d.ts,
            resolving symbol AppModule in /home/osboxes/Desktop/my_app/.tmp/app/app.module.ts, resolving symbol 
            AppModule in /home/osboxes/Desktop/my_app/.tmp/app/app.module.ts 
[11:46:48]  ngc failed 
[11:46:48]  ionic-app-script task: "build" 
[11:46:48]  Error: Error 
```
I tried to commands `ionic build android` and `ionic build android --test`
my package.json file:
```
...
  "scripts": {
    "ionic:build": "node copy-env-config.js --env test | ionic-app-scripts build",
    "ionic:serve": "node copy-env-config.js --env test | ionic-app-scripts serve"
  },
...
```
ionic info:
```
$ ionic info

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.5.0
Xcode version: Not installed
```

**Comment by mvidailhet** [comment]
Hi! 
Thanks for your interest in this module @tomysmile @mosinski 

I get the same error as you in production. I'm trying to understand where the problems comes from. I'm pretty new to Angular2, so I'm a bit confused by this.

I'll let you know once i find the problem. Of course, If you have an idea of how to resolve it, I'm all ears!

**Comment by sandorfr** [comment]
@mvidailhet  I believe this has to do with `metadata.json`. see https://github.com/angular/angular/issues/11262  and especially https://github.com/angular/angular/issues/11262#issuecomment-248521925
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  },
  "files": [
    "app/app.module.ts",
    "app/main.ts"
  ],
  "angularCompilerOptions": {
   "genDir": "aot",
   "skipMetadataEmit" : false
 }
}
```

I think `emitDecoratorMetadata` is actually missing in current `tsconfig`

**Comment by mvidailhet** [comment]
@sandorfr I tried setting it to false, I get the same error. Setting it to true only gives me a less precise error : "Error: Unexpected value 'GLIonic2EnvConfigurationModule' imported by the module 'AppModule'"

**Comment by mvidailhet** [comment]
I'm actually basing this module on this [Ionic module template](https://github.com/driftyco/ionic-module-template). And I'm getting the same error when building in production. I'm asking for help there and referencing this issue.

Hope someone will be able to enlighten me on this error.

**Comment by mvidailhet** [comment]
OK guys, so I updated the node_modules and it works now, so you can install the latest version of the module and it should work.

Note that it seems to not be working with old app-scripts versions of Ionic. Install the latest (1.0.0) to make it work.

Feedbacks are welcome!

**Comment by tomysmile** [comment]
perfect, will try it for sure. thanks Michel :)
