### ISSUE TITLE
livereload doesn't work

### ISSUE THREAD

**Issue by nicolaszein** [geeklearningio/gl-ionic2-env-configuration#5]
After I've installed, the livereload stop working.

Anyone with this problem?

**Comment by PunkHaz4rd** [comment]
Yeah me too.

**Comment by sandorfr** [comment]
Are you using Angular CLI?

**Comment by mvidailhet** [comment]
Sorry guys. I was hands deep in Ionic1 applications and couldn't find the time to work on this.

I launched a livereload with my Android device and this provider and everything worked.

Do this still breaks the livereload? Can you reproduce the steps?
